"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Label } from "@/components/ui/label";
import { Download, FileText, Table } from "lucide-react";
import { exportToCSV, type TableRow } from "@/lib/mock-data";

interface ExportDialogProps {
  data: TableRow[];
  filename?: string;
}

export function ExportDialog({ data, filename = "campaigns" }: ExportDialogProps) {
  const [format, setFormat] = useState<"csv" | "pdf">("csv");
  const [isExporting, setIsExporting] = useState(false);
  const [open, setOpen] = useState(false);

  const exportToPDF = (data: TableRow[], filename: string) => {
    // Create HTML content for PDF
    const htmlContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>${filename}</title>
        <style>
          body { font-family: Arial, sans-serif; margin: 20px; }
          h1 { color: #333; border-bottom: 2px solid #333; padding-bottom: 10px; }
          table { width: 100%; border-collapse: collapse; margin-top: 20px; }
          th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
          th { background-color: #f2f2f2; font-weight: bold; }
          tr:nth-child(even) { background-color: #f9f9f9; }
          .summary { background-color: #e7f3ff; padding: 15px; margin: 20px 0; border-radius: 5px; }
          .footer { margin-top: 30px; text-align: center; color: #666; font-size: 12px; }
        </style>
      </head>
      <body>
        <h1>Campaign Performance Report</h1>
        <div class="summary">
          <strong>Report Summary:</strong><br>
          Total Campaigns: ${data.length}<br>
          Total Revenue: $${data.reduce((sum, item) => sum + item.revenue, 0).toLocaleString()}<br>
          Total Cost: $${data.reduce((sum, item) => sum + item.cost, 0).toLocaleString()}<br>
          Average ROI: ${(data.reduce((sum, item) => sum + item.roi, 0) / data.length).toFixed(2)}%<br>
          Generated: ${new Date().toLocaleDateString()}
        </div>
        <table>
          <thead>
            <tr>
              <th>Campaign</th>
              <th>Platform</th>
              <th>Impressions</th>
              <th>Clicks</th>
              <th>CTR (%)</th>
              <th>Cost ($)</th>
              <th>Conversions</th>
              <th>Revenue ($)</th>
              <th>ROI (%)</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
            ${data.map(row => `
              <tr>
                <td>${row.campaign}</td>
                <td>${row.platform}</td>
                <td>${row.impressions.toLocaleString()}</td>
                <td>${row.clicks.toLocaleString()}</td>
                <td>${row.ctr.toFixed(2)}</td>
                <td>${row.cost.toLocaleString()}</td>
                <td>${row.conversions.toLocaleString()}</td>
                <td>${row.revenue.toLocaleString()}</td>
                <td>${row.roi.toFixed(2)}</td>
                <td style="text-transform: capitalize;">${row.status}</td>
              </tr>
            `).join('')}
          </tbody>
        </table>
        <div class="footer">
          Report generated by Analytics Dashboard
        </div>
      </body>
      </html>
    `;

    // Create a new window for printing
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(htmlContent);
      printWindow.document.close();
      
      // Wait for content to load then print
      printWindow.onload = () => {
        printWindow.print();
        // Close the window after printing (optional)
        setTimeout(() => {
          printWindow.close();
        }, 1000);
      };
    } else {
      // Fallback: download as HTML file if popup blocked
      const blob = new Blob([htmlContent], { type: 'text/html' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `${filename}.html`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
    }
  };

  const handleExport = async () => {
    setIsExporting(true);
    
    try {
      if (format === "csv") {
        exportToCSV(data, filename);
      } else {
        exportToPDF(data, filename);
      }
      
      // Simulate export delay
      await new Promise(resolve => setTimeout(resolve, 1500));
      setOpen(false);
    } catch (error) {
      console.error("Export failed:", error);
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button variant="outline" size="icon" className="transition-all duration-200 hover:scale-105">
          <Download className="h-4 w-4" />
        </Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Download className="h-5 w-5" />
            Export Data
          </DialogTitle>
          <DialogDescription>
            Export your campaign data in your preferred format.
          </DialogDescription>
        </DialogHeader>
        
        <div className="space-y-4 py-4">
          <div className="space-y-2">
            <Label htmlFor="format">Export Format</Label>
            <Select value={format} onValueChange={(value: "csv" | "pdf") => setFormat(value)}>
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="csv">
                  <div className="flex items-center gap-2">
                    <Table className="h-4 w-4" />
                    CSV File
                  </div>
                </SelectItem>
                <SelectItem value="pdf">
                  <div className="flex items-center gap-2">
                    <FileText className="h-4 w-4" />
                    PDF Report
                  </div>
                </SelectItem>
              </SelectContent>
            </Select>
          </div>
          
          <div className="text-sm text-muted-foreground">
            <p>Records to export: <span className="font-medium">{data.length}</span></p>
            <p>File name: <span className="font-medium">{filename}.{format}</span></p>
          </div>
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={() => setOpen(false)} disabled={isExporting}>
            Cancel
          </Button>
          <Button onClick={handleExport} disabled={isExporting}>
            {isExporting ? (
              <>
                <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white mr-2" />
                Exporting...
              </>
            ) : (
              <>
                <Download className="h-4 w-4 mr-2" />
                Export {format.toUpperCase()}
              </>
            )}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}